enum LoginErrorCodes {
  INACTIVE_USER = 'ID_COMMON_INACTIVE_ACCOUNT_ERROR',
  INVALID_USER = 'ID_COMMON_AUTHENTICATION_ERROR',
  BLOCKED_USER = 'ID_COMMON_BLOCK_ACCOUNT_ERROR',
}

export default LoginErrorCodes
