enum ProtocolStatuses {
  WAITING_APPROVAL = 1, //"TƏSDIQ GÖZLƏYIR"
  APPROVED, // "TƏSDIQ EDILMIŞ"
  CANCELLED, // "LƏĞV EDILMIŞ"
  REFUSED, // "XITAM VERILMIŞ"
  PROLONGED, // "QƏRAR UZADILMIŞ"
  SUSPENDED, // "QƏRAR DAYANDIRILMIŞ"
  WARNED, // "XƏBARDAR EDILIB"
  CONDITIONAL_PENALTY, // "ŞƏRTI CƏRIMƏ"
  PAID, //"ÖDƏNILMIŞ"
  SENT_RESPECTIVELY, // "AIDIYYATI ÜZRƏ GÖNDƏRILMIŞ"
}

export default ProtocolStatuses
